# Generated by Django 5.2.1 on 2025-05-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='product_images/empty.png', null=True, upload_to='product_images/'),
        ),
    ]
